//! Emits the table of vendored query files, by scanning the vendored tree.
//!
//! # Why a scan, when the manifests beside these are hand-listed
//!
//! `manifest/embedded.rs` names its `config.toml` entries one by one on
//! purpose: the *set of languages* must not depend on what happens to be on
//! disk, or a vendor refresh that dropped a directory would remove a language
//! with no diff saying so. That argument still holds and this script does not
//! touch it — the language set stays hand-listed there.
//!
//! The question this script answers is a different one: *which `.scm` files
//! does each language ship?* That is 21 languages against 6 query kinds, and
//! the answer is a plain fact about the directory. It cannot be written as a
//! macro either, because `include_str!` is a compile error on a missing file —
//! so "does this language ship `brackets.scm`?" is unaskable from inside Rust
//! and has to be answered by something that can look.
//!
//! Hand-writing it instead would mean adding a language required editing a
//! 126-entry table, which is exactly the hard-coding this work exists to
//! remove.
//!
//! # The table is keyed by file name, not by position
//!
//! The emitted rows carry `("highlights.scm", <text>)` rather than relying on
//! an agreed ordering of query kinds. That is deliberate: a positional table
//! would mean this script and `query/kind.rs` each held a copy of the kind
//! order, and two copies of one ordering that agree today are a defect waiting
//! for someone to insert a kind in the middle. Keying by name leaves exactly
//! one shared fact — the file name — which `QueryKind::file_name` already
//! owns and this script reads off the directory rather than restating.
//!
//! It also means a language may ship a `.scm` Iridium has no kind for. Those
//! are carried and never asked for, which is the correct handling: AWL ships a
//! `folds.scm`, and a scan that rejected unknown files would fail the build
//! over a file nothing reads.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs, io};

/// The vendored tree, relative to the crate root.
const QUERIES: &str = "src/languages/queries";

/// The hand-edited language list, relative to the crate root.
const LANGUAGES: &str = "src/languages/languages.txt";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let out_dir = env::var("OUT_DIR")?;

    emit_language_table(Path::new(&manifest_dir), Path::new(&out_dir))?;

    let queries = Path::new(&manifest_dir).join(QUERIES);

    // Rebuild when a query file is added, removed or edited. Cargo watches a
    // named directory shallowly, so every language directory is named too —
    // without that, adding `highlights.scm` to an existing language would not
    // trigger a rebuild and the stale table would survive.
    println!("cargo:rerun-if-changed={}", queries.display());

    let table = scan(&queries)?;

    let mut out = String::from(
        // `pub`, not `pub(crate)`, and the difference from `LANGUAGE_IDS`
        // below is not an inconsistency. This is included into `query/embedded`,
        // a *private* module, so `pub` is already unreachable from outside the
        // crate and `pub(crate)` would be redundant — clippy's
        // `redundant_pub_crate` rejects it. `LANGUAGE_IDS` is included into the
        // crate root, where the restriction is real and has to be spelled.
        "// @generated by build.rs from src/languages/queries. Do not edit.\n\
         /// Every vendored `.scm`, as `(language directory, [(file name, text)])`.\n\
         pub static QUERY_SOURCES: &[(&str, &[(&str, &str)])] = &[\n",
    );

    for (language, files) in &table {
        writeln!(out, "    ({language:?}, &[")?;
        for (name, path) in files {
            writeln!(out, "        ({name:?}, include_str!({path:?})),")?;
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    fs::write(Path::new(&out_dir).join("query_sources.rs"), out)?;
    Ok(())
}

/// Emits the language id table and the `Language::<Name>` constants.
///
/// Sorted by id, so the index space — which `iridium-syntax` indexes its
/// compiled-query cache by — is a function of the ids alone. Moving a line in
/// `languages.txt` therefore cannot shift a language's index, and a reviewer
/// does not have to check the ordering of that file for correctness.
fn emit_language_table(
    manifest_dir: &Path,
    out_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let list = manifest_dir.join(LANGUAGES);
    println!("cargo:rerun-if-changed={}", list.display());

    let text = fs::read_to_string(&list)?;
    let mut languages = Vec::new();

    for (number, line) in text.lines().enumerate() {
        let line = line.split('#').next().unwrap_or_default().trim();
        if line.is_empty() {
            continue;
        }
        let mut columns = line.split_whitespace();
        let (Some(id), Some(constant), None) = (columns.next(), columns.next(), columns.next())
        else {
            return Err(format!(
                "{}:{}: expected exactly two columns, `<id> <constant>`, got {line:?}",
                list.display(),
                number + 1
            )
            .into());
        };
        languages.push((id.to_owned(), constant.to_owned()));
    }

    languages.sort();

    // A duplicate id would give two constants the same index, so two languages
    // would silently be one. Cheaper to refuse than to explain later.
    for pair in languages.windows(2) {
        if pair[0].0 == pair[1].0 {
            return Err(format!("{}: {:?} is listed twice", list.display(), pair[0].0).into());
        }
    }

    let mut out =
        String::from("// @generated by build.rs from src/languages/languages.txt. Do not edit.\n");

    out.push_str("/// Every language id, in the index space `Language::index` returns.\npub(crate) static LANGUAGE_IDS: &[&str] = &[\n");
    for (id, _) in &languages {
        writeln!(out, "    {id:?},")?;
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// The languages, named. These replace what were enum variants, and keep\n\
         /// their exact spelling so that `Language::Rust` still reads the same at\n\
         /// every call site — including in patterns, since a newtype over `u16`\n\
         /// with derived `PartialEq`/`Eq` is structural-match.\n\
         #[expect(\n\
         \x20   non_upper_case_globals,\n\
         \x20   reason = \"these replace enum variants and keep their spelling, so the ~200 call sites that name them do not have to change\"\n\
         )]\n\
         impl Language {\n",
    );
    for (index, (id, constant)) in languages.iter().enumerate() {
        writeln!(out, "    /// The `{id}` language.")?;
        writeln!(out, "    pub const {constant}: Self = Self({index});")?;
    }
    out.push_str("}\n\n");

    out.push_str(
        "/// Every language, in the index space. Named through the constants so\n\
         /// that a mistake in the emitted indices shows up as a name that does\n\
         /// not exist rather than as a silently wrong ordering.\n\
         static ALL: &[Language] = &[\n",
    );
    for (_, constant) in &languages {
        writeln!(out, "    Language::{constant},")?;
    }
    out.push_str("];\n");

    fs::write(out_dir.join("language_table.rs"), out)?;
    Ok(())
}

/// Each language directory against its `.scm` files, as `(file name, absolute path)`.
type Table = BTreeMap<String, Vec<(String, String)>>;

/// Reads every language directory's `.scm` files.
///
/// `BTreeMap`, and each file list sorted: a directory listing has no order, and
/// an unordered table would make the generated file differ between machines and
/// between builds for no reason.
///
/// The paths are absolute because the generated file is included from `OUT_DIR`,
/// which is nowhere near the vendored tree — a relative `include_str!` would
/// resolve against the wrong directory entirely.
fn scan(queries: &Path) -> io::Result<Table> {
    let mut table = Table::new();

    for entry in fs::read_dir(queries)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let directory = entry.path();
        let Some(language) = entry.file_name().to_str().map(str::to_owned) else {
            // A non-UTF-8 directory name cannot be a language id, which is
            // `&'static str` everywhere. Skipping is right: this is a vendored
            // tree and such a name would be a packaging accident, not a
            // language someone is waiting on.
            continue;
        };

        println!("cargo:rerun-if-changed={}", directory.display());

        let mut files = Vec::new();
        for file in fs::read_dir(&directory)? {
            let file = file?;
            let path = file.path();
            if path.extension().is_none_or(|extension| extension != "scm") {
                continue;
            }
            let (Some(name), Some(path)) = (
                file.file_name().to_str().map(str::to_owned),
                path.to_str().map(str::to_owned),
            ) else {
                continue;
            };
            files.push((name, path));
        }

        files.sort();
        table.insert(language, files);
    }

    Ok(table)
}
