/**
 * Generates TypeScript file with inlined grammar WASM data as base64.
 * Run this before building to embed grammars into the bundle.
 */

const GRAMMARS_DIR = new URL("../grammars", import.meta.url).pathname;
const OUTPUT_FILE = new URL("../ts/syntax/grammars.gen.ts", import.meta.url).pathname;

const LANGUAGES = [
  "rust",
  "typescript",
  "tsx",
  "javascript",
  "python",
  "go",
  "json",
  "yaml",
  "css",
  "html",
  "cpp",
  "toml",
  "lua",
];

function toBase64(data: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return btoa(binary);
}

async function main() {
  console.log("Inlining grammar WASMs...");

  const grammars: Record<string, string> = {};
  let totalSize = 0;

  for (const lang of LANGUAGES) {
    const filename = `tree-sitter-${lang}.wasm`;
    const filepath = `${GRAMMARS_DIR}/${filename}`;

    try {
      const data = await Deno.readFile(filepath);
      const base64 = toBase64(data);
      grammars[lang] = base64;
      totalSize += data.length;
      console.log(`  ${lang}: ${(data.length / 1024).toFixed(1)} KB`);
    } catch {
      console.error(`  ${lang}: MISSING`);
    }
  }

  const output = `/**
 * Auto-generated file - do not edit manually.
 * Generated by scripts/inline-grammars.ts
 *
 * Contains base64-encoded tree-sitter grammar WASM files.
 */

export const GRAMMAR_DATA: Record<string, string> = ${JSON.stringify(grammars, null, 2)};

/**
 * Decode base64 grammar data to Uint8Array.
 */
export function decodeGrammar(lang: string): Uint8Array | null {
  const base64 = GRAMMAR_DATA[lang];
  if (!base64) return null;

  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

export const AVAILABLE_LANGUAGES = ${JSON.stringify(LANGUAGES)} as const;
`;

  await Deno.writeTextFile(OUTPUT_FILE, output);
  console.log(`\nGenerated: ${OUTPUT_FILE}`);
  console.log(`Total grammar size: ${(totalSize / 1024 / 1024).toFixed(2)} MB`);
}

await main();
