/**
 * The syntax bundle format: how a wasm payload is embedded in a generated
 * `.ts` file, and the loader emitted beside it to get the bytes back.
 *
 * This lives apart from `build.ts` for one reason: `build.ts` clones nineteen
 * grammar repositories and shells out to the tree-sitter CLI, so nothing in it
 * can be exercised without a network. The encoding is the half that has
 * actually broken, and it is pure — bytes in, source text out — so it is
 * testable on its own. `bundle.test.ts` generates a module from known bytes,
 * imports it, and asks the emitted loader for them back.
 *
 * ⚠️ The payloads are gzipped. Raw base64 of the same grammars is 21.9 MB
 * against 2.1 MB compressed, and all of it lands in the browser payload. The
 * compression step and the matching loader were both lost from the builder at
 * some point after 14 January 2026 and restored on 8 August; the only surviving
 * evidence that they had ever existed was inside a file stamped
 * `DO NOT EDIT MANUALLY`. Anyone editing the encoder must edit the loader to
 * match, and the round-trip check is what refuses to let them drift.
 */

import { gunzipSync, gzipSync } from "node:zlib";

/** One built grammar, ready to embed. */
export interface GrammarPayload {
  /** The language id the bundle is keyed by, e.g. `"rust"`. */
  lang: string;
  /** The compiled `.wasm` bytes. */
  wasm: Uint8Array;
}

/** Where a size report goes. Injected so a test can stay quiet. */
export type Report = (message: string) => void;

/**
 * Gzip a payload and base64 it for embedding, checking on the way out that it
 * decompresses back to exactly what went in.
 *
 * The check is not paranoia about zlib — it is cheap insurance against the
 * *silent* half of this failure. A bundle built with the compression dropped
 * still builds, still type-checks, and fails only in a browser at grammar load,
 * having quietly multiplied the payload tenfold on the way.
 *
 * @throws if the round trip does not reproduce the input byte for byte.
 */
export function encodePayload(
  what: string,
  bytes: Uint8Array,
  report: Report = console.log
): string {
  const compressed = gzipSync(bytes, { level: 9 });
  const restored = gunzipSync(compressed);
  if (!restored.equals(Buffer.from(bytes))) {
    throw new Error(
      `${what}: gzip round trip did not reproduce the input ` +
        `(${bytes.length} B in, ${restored.length} B out)`
    );
  }
  report(
    `  📦 ${what}: ${(bytes.length / 1024).toFixed(1)} KB → ` +
      `${(compressed.length / 1024).toFixed(1)} KB gzipped ` +
      `(${(bytes.length / compressed.length).toFixed(1)}×)`
  );
  return Buffer.from(compressed).toString("base64");
}

/**
 * The body of an emitted loader, shared by both generated files so the two
 * cannot drift apart. `source` is the expression holding the base64; the
 * snippet ends with the decoded bytes in a local named `result`.
 *
 * `DecompressionStream` rather than a bundled inflate: it is the platform's
 * own, present in every browser this editor targets, and it keeps the
 * generated bundle's runtime dependencies at zero. It is also why the loaders
 * are `async` — there is no synchronous gunzip on the web platform.
 */
export function decompressBody(source: string): string {
  return `  const binary = atob(${source});
  const compressed = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    compressed[i] = binary.charCodeAt(i);
  }

  const ds = new DecompressionStream("gzip");
  const writer = ds.writable.getWriter();
  writer.write(compressed);
  writer.close();

  const chunks: Uint8Array[] = [];
  const reader = ds.readable.getReader();
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }

  const totalLength = chunks.reduce((sum, c) => sum + c.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }`;
}

/** Generates `core.gen.ts` — the web-tree-sitter runtime itself. */
export function generateCoreTs(
  coreWasm: Uint8Array,
  webTreeSitterVersion: string,
  date: string,
  report: Report = console.log
): string {
  const base64 = encodePayload("core wasm", coreWasm, report);

  return `/**
 * Auto-generated tree-sitter core WASM (gzip-compressed).
 * Generated by: packages/tree-sitter-builder
 * Date: ${date}
 * Version: web-tree-sitter@${webTreeSitterVersion}
 *
 * DO NOT EDIT MANUALLY
 */

const CORE_WASM_BASE64 = "${base64}";

/**
 * Decode the gzip-compressed tree-sitter core WASM binary.
 */
export async function decodeCoreWasm(): Promise<Uint8Array> {
${decompressBody("CORE_WASM_BASE64")}
  return result;
}
`;
}

/** Generates `grammars.gen.ts` — every compiled grammar, keyed by language. */
export function generateGrammarsTs(
  payloads: GrammarPayload[],
  date: string,
  report: Report = console.log
): string {
  let code = `/**
 * Auto-generated tree-sitter grammar bundles (gzip-compressed).
 * Generated by: packages/tree-sitter-builder
 * Date: ${date}
 *
 * DO NOT EDIT MANUALLY
 */

export const AVAILABLE_LANGUAGES = [
${payloads.map((p) => `  "${p.lang}",`).join("\n")}
] as const;

const GRAMMAR_DATA: Record<string, string> = {
`;

  for (const payload of payloads) {
    const base64 = encodePayload(`${payload.lang} grammar`, payload.wasm, report);
    code += `  "${payload.lang}": "${base64}",\n`;
  }

  code += `};

/**
 * Decode a gzip-compressed grammar from base64 to Uint8Array.
 */
export async function decodeGrammar(lang: string): Promise<Uint8Array | null> {
  const data = GRAMMAR_DATA[lang];
  if (!data) return null;

${decompressBody("data")}
  return result;
}
`;

  return code;
}
