//! Which language a document is written in.
//!
//! Identity only: a registry of languages, each one's stable identifier, and
//! the functions that map a string onto one. Nothing here parses anything, and
//! this crate depends on nothing that does.
//!
//! The registry is generated at build time from `src/languages/languages.txt`
//! and the vendored tree beside it — see `build.rs`. [`Language`] was a closed
//! enum until then, which meant every language had to be named in five separate
//! exhaustive matches and a language with queries and a manifest but no grammar
//! could not be represented at all.
//!
//! # Why this is its own crate
//!
//! Language *identity* is needed in configurations that have no parser.
//! `iridium-editor` built without its `syntax` feature carries no tree-sitter
//! at all, and yet still has to know that a document is Rust: comment
//! toggling, indent rules and auto-pairs all key off the language and none of
//! them involves a syntax tree.
//!
//! Before this crate existed there were **two** `Language` enums — the real
//! one in `iridium-syntax` and a hand-maintained stub in `iridium-editor`,
//! selected by that feature. They disagreed, quietly and in both directions:
//!
//! - the real `from_id` accepted aliases (`rs`, `py`, `golang`, `zsh`) and
//!   lower-cased its input; the stub matched canonical ids exactly and
//!   case-sensitively, so `from_id("rs")` was `Some(Rust)` in one build and
//!   `None` in the other;
//! - the real `from_extension` knew `.pyw` and the stub did not; the stub knew
//!   `.jsonc` and the real one did not. Collapsing the two took the real one's
//!   answer, which left `.jsonc` resolving to nothing at all; the grammar was
//!   then checked and it turned out the stub had been right, so `.jsonc` is
//!   back — see `MANIFEST_ALIASES` in the crate's `suffix` module for how
//!   it resolves now;
//! - the real enum derived `Serialize`/`Deserialize` and the stub did not, so
//!   a value that round-tripped through a configuration in one build would not
//!   compile in the other.
//!
//! None of that could be caught by a test, because the two types are feature
//! *alternatives*: no build has both in scope, so nothing could compare them.
//! A guard was structurally impossible, which is why the answer is one type
//! rather than two copies and a check.
//!
//! The divergence had already produced a live defect — see the note on
//! `language_tokens` in `iridium-editor`, where the comment-syntax table was
//! gated on the same feature and answered "this language has no comments" for
//! every language in the parser-free build.
//!
//! # What else lives here
//!
//! The vendored `languages/` tree, and [`query`], which serves its `.scm`
//! files as text. That is data about languages, not a parser — this crate
//! still depends on nothing that parses anything — and it is here for the same
//! reason the registry is: the `config.toml` manifests sitting beside those
//! queries describe comment syntax, brackets and file associations, all of
//! which the parser-free build needs. Splitting the directory so only the
//! manifests came along would leave one vendored upstream tree owned by two
//! crates, and the next refresh would have to know that.
//!
//! [`manifest`] reads those files; a private `suffix` module turns their file
//! associations into an answer to "what language is this path?". Between them they are why
//! this crate no longer hand-maintains a single fact about a language that the
//! vendored tree already states.

use std::fmt;
use std::path::Path;

use serde::{Deserialize, Serialize};

pub mod manifest;
pub mod query;
mod suffix;

// `LANGUAGE_IDS`, `ALL` and the `Language::<Name>` constants, generated by
// `build.rs` from `src/languages/languages.txt`. Adding a language is a line in
// that file and a directory beside it — no Rust to edit, which is the whole
// point of the registry.
include!(concat!(env!("OUT_DIR"), "/language_table.rs"));

/// A language a document can be written in.
///
/// An index into the generated registry rather than an enum, so that the set of
/// languages is data. It was a closed enum until the registry landed, and the
/// cost of that was concrete: every language had to be named in five separate
/// exhaustive matches, and a language Iridium had queries and a manifest for
/// but no grammar could not be represented at all.
///
/// The named constants — [`Language::Rust`] and the rest — keep the exact
/// spelling the variants had, so nothing that names one had to change, and they
/// remain usable in patterns. What a `match` over them loses is exhaustiveness:
/// it needs a wildcard arm, because the list is no longer fixed at the point
/// the match is written.
///
/// A language in the registry may have no grammar linked. That is a real and
/// useful state, not a defect: file association, comment tokens, indent rules
/// and auto-pairs all come from the manifest and none of them needs a parser.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Language(u16);

impl fmt::Debug for Language {
    /// Prints the identifier, not the index.
    ///
    /// Written rather than derived because a derived one prints `Language(9)`,
    /// and `{language:?}` is what nearly every test failure message in the
    /// workspace uses to say *which* language it was talking about.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Language").field(&self.id()).finish()
    }
}

impl Serialize for Language {
    /// Writes the identifier.
    ///
    /// Byte-identical to what the enum's `#[serde(rename_all = "lowercase")]`
    /// produced for all thirteen — `Tsx` was `"tsx"`, `Cpp` was `"cpp"`,
    /// `JavaScript` was `"javascript"` — which is exactly what [`Language::id`]
    /// returns. That equality is not a coincidence to be relied on quietly: a
    /// document saved by one face is read back by another, so a test pins it.
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.id())
    }
}

impl<'de> Deserialize<'de> for Language {
    /// Reads an identifier, refusing one no language claims.
    ///
    /// Refusing rather than preserving the unknown string is deliberate: a
    /// configuration naming a language that does not exist should be an error
    /// where it is written, not a value that round-trips silently and produces
    /// a document nothing can highlight.
    ///
    /// Deserializes through `String` rather than `&str` because a borrowed
    /// `&str` fails on any format that cannot borrow — a JSON string
    /// containing an escape, for one — and this runs on the path that loads a
    /// user's configuration.
    ///
    /// **This accepts more than the derived implementation did.** That one was
    /// `#[serde(rename_all = "lowercase")]` and took the canonical spelling
    /// exactly; going through [`Language::from_id`] means `"Rust"`, `"RUST"`
    /// and `"rs"` are now all read as Rust. Widening deliberately: the thing
    /// being read is usually a hand-written configuration file, and the same
    /// generosity already applied when a language was named through any other
    /// route. Writing is unchanged, so a value that arrives as `"rs"` is
    /// written back as `"rust"` — the round trip normalises rather than
    /// preserving what was typed.
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let id = String::deserialize(deserializer)?;
        Self::from_id(&id)
            .ok_or_else(|| serde::de::Error::custom(format!("unknown language identifier {id:?}")))
    }
}

/// Spellings that mean a language but are not its identifier.
///
/// Kept as data beside the registry rather than as arms of a match, for the
/// same reason the languages themselves are. Case is folded before this is
/// consulted, so every alias here is lower-case.
///
/// Deliberately generous: this is what a hand-written configuration file and a
/// host API are both read through, and refusing `rs` because the canonical
/// spelling is `rust` would be pedantry with no upside.
const ALIASES: &[(&str, &str)] = &[
    ("rs", "rust"),
    ("py", "python"),
    ("ts", "typescript"),
    ("js", "javascript"),
    ("golang", "go"),
    ("yml", "yaml"),
    ("md", "markdown"),
    ("sh", "bash"),
    ("shell", "bash"),
    ("zsh", "bash"),
    ("c++", "cpp"),
    ("cxx", "cpp"),
    ("cc", "cpp"),
];

impl Language {
    /// How many languages there are.
    ///
    /// Still a compile-time constant: the registry is generated at build time,
    /// so the count is known then. That is what lets `iridium-syntax` keep
    /// sizing its compiled-query cache as a plain array, with no allocation and
    /// no lock on the read path.
    pub const COUNT: usize = LANGUAGE_IDS.len();

    /// The stable identifier — the spelling used in a configuration file, a
    /// serialized document, and across the language boundary to TypeScript.
    #[must_use]
    pub const fn id(&self) -> &'static str {
        LANGUAGE_IDS[self.0 as usize]
    }

    /// Parses a language from its identifier, or a common alias for one.
    ///
    /// Case-insensitive. Aliases are resolved to a canonical id first, then
    /// looked up once — so an alias can never name a language the registry does
    /// not have without that being a lookup failure like any other.
    #[must_use]
    pub fn from_id(id: &str) -> Option<Self> {
        let lowered = id.to_lowercase();

        let canonical = ALIASES
            .iter()
            .find(|(alias, _)| *alias == lowered)
            .map_or(lowered.as_str(), |(_, canonical)| *canonical);

        LANGUAGE_IDS
            .iter()
            .position(|&known| known == canonical)
            .and_then(|index| u16::try_from(index).ok())
            .map(Self)
    }

    /// The file extensions this language claims, without leading dots.
    ///
    /// Read from the language's vendored manifest rather than written out here
    /// — see the crate's `suffix` module for what that entails, including the whole file
    /// names the manifest also carries and the one case-sensitivity that
    /// matters.
    ///
    /// Returns an iterator rather than a slice because the list is assembled
    /// from up to three sources and no longer exists as one contiguous array.
    pub fn extensions(self) -> impl Iterator<Item = &'static str> {
        crate::suffix::extensions_of(self)
    }

    /// Detects a language from a file extension, without the leading dot.
    ///
    /// Case-sensitive first and case-insensitive second, so `README.MD` is
    /// Markdown while `.C` stays C++ and `.c` stays C. The crate's `suffix`
    /// module has the reason that ordering is load-bearing, not incidental.
    ///
    /// The search is linear over [`Self::all`], which is a few dozen string
    /// comparisons on the path that opens a file — not on any path that runs
    /// per keystroke or per frame.
    #[must_use]
    pub fn from_extension(ext: &str) -> Option<Self> {
        crate::suffix::language_for_extension(ext)
    }

    /// Detects a language from a whole file name — `main.rs`, `flake.lock`,
    /// `.bashrc`.
    ///
    /// Strictly more capable than [`Self::from_extension`], which it subsumes:
    /// an extension is just the tail of a name after a dot. Prefer it wherever
    /// a name is available, because the vendored manifests claim files that
    /// have no extension for `Path::extension` to return — `.env`,
    /// `flake.lock`, `bun.lock`, `tsconfig.json`, `PKGBUILD`, `.bashrc`.
    #[must_use]
    pub fn from_file_name(file_name: &str) -> Option<Self> {
        crate::suffix::language_for_file_name(file_name)
    }

    /// Detects a language from a path, by its file name.
    ///
    /// This is what a face opening a file should call. Returns `None` for a
    /// path with no file name at all, and for a name nothing claims.
    #[must_use]
    pub fn for_path(path: &Path) -> Option<Self> {
        Self::from_file_name(path.file_name()?.to_str()?)
    }

    /// Every language, in the order that is this type's index space.
    ///
    /// The order is part of the contract, not a presentation detail:
    /// `iridium-syntax` indexes its compiled-query cache by position here. It
    /// is the identifiers sorted, so it is a function of the ids alone —
    /// reordering `languages.txt` cannot move a language's index.
    ///
    /// A slice rather than an array of `COUNT` now that the length comes from
    /// the generated table. The array type used to guarantee structurally that
    /// this had exactly `COUNT` entries; a test asserts it instead.
    #[must_use]
    pub const fn all() -> &'static [Self] {
        ALL
    }

    /// This language's position in [`Language::all`].
    ///
    /// The index *is* the value, so this cannot disagree with `all()` the way
    /// a hand-written match could — which is what the old one needed a test to
    /// rule out.
    #[must_use]
    pub const fn index(self) -> usize {
        self.0 as usize
    }

    /// This language's vendored manifest, if one was vendored for it.
    ///
    /// Every variant has one today and a test asserts it, but the return type
    /// is an `Option` rather than a bare reference because the manifests are a
    /// vendored upstream tree: a refresh can drop a directory, and that should
    /// cost a caller a `None` to handle rather than this crate a panic.
    #[must_use]
    pub fn manifest(self) -> Option<&'static manifest::Manifest> {
        manifest::by_id(self.id())
    }
}

#[cfg(test)]
mod tests {
    use super::Language;

    #[test]
    fn every_language_round_trips_through_its_identifier() {
        for &language in Language::all() {
            assert_eq!(
                Language::from_id(language.id()),
                Some(language),
                "{language:?} does not survive its own id"
            );
        }
    }

    #[test]
    fn index_agrees_with_the_order_of_all() {
        for (position, &language) in Language::all().iter().enumerate() {
            assert_eq!(language.index(), position, "{language:?}");
        }
    }

    #[test]
    fn identifiers_are_distinct() {
        let mut seen: Vec<&str> = Language::all().iter().map(Language::id).collect();
        seen.sort_unstable();
        let count = seen.len();
        seen.dedup();
        assert_eq!(seen.len(), count, "two languages share an identifier");
    }

    #[test]
    fn an_identifier_is_read_whatever_its_case() {
        // A configuration file is written by hand, and `Rust` is what somebody
        // writes when they are naming a language rather than an identifier.
        assert_eq!(Language::from_id("Rust"), Some(Language::Rust));
        assert_eq!(Language::from_id("RUST"), Some(Language::Rust));
    }

    #[test]
    fn common_aliases_resolve() {
        assert_eq!(Language::from_id("rs"), Some(Language::Rust));
        assert_eq!(Language::from_id("py"), Some(Language::Python));
        assert_eq!(Language::from_id("golang"), Some(Language::Go));
        assert_eq!(Language::from_id("zsh"), Some(Language::Bash));
        assert_eq!(Language::from_id("c++"), Some(Language::Cpp));
    }

    #[test]
    fn an_unknown_identifier_is_none_rather_than_a_guess() {
        assert_eq!(Language::from_id("cobol"), None);
        assert_eq!(Language::from_id(""), None);
    }

    #[test]
    fn extensions_are_read_whatever_their_case() {
        assert_eq!(Language::from_extension("RS"), Some(Language::Rust));
        assert_eq!(Language::from_extension("MD"), Some(Language::Markdown));
    }

    #[test]
    fn header_extensions_belong_to_cpp() {
        // `.h` used to be C here, with a comment conceding the ambiguity. The
        // vendored manifests give it to C++ — its `cpp` claims `h` and its `c`
        // does not — and that is also the better answer, because the C++
        // grammar is a superset: it parses a C header, where the C grammar
        // fails on a template or a namespace. See `suffix::tests` for the
        // `.C` / `.c` pair, which is the case where one letter is two
        // languages.
        assert_eq!(Language::from_extension("h"), Some(Language::Cpp));
        assert_eq!(Language::from_extension("hpp"), Some(Language::Cpp));
        assert_eq!(Language::from_extension("hh"), Some(Language::Cpp));
        assert_eq!(Language::from_extension("c"), Some(Language::C));
    }

    #[test]
    fn jsonc_is_json_but_is_not_an_identifier() {
        // The extension resolves, because a `.jsonc` file wants the JSON
        // grammar and that grammar parses its comments.
        assert_eq!(Language::from_extension("jsonc"), Some(Language::Json));
        assert_eq!(Language::from_extension("JSONC"), Some(Language::Json));

        // The *identifier* deliberately does not, because nothing produces it:
        // a face sets a document's language from `id()`, which is `"json"`.
        // Accepting `"jsonc"` here would claim a name this type never emits and
        // that no serialized document can contain.
        assert_eq!(Language::from_id("jsonc"), None);
        assert_eq!(Language::Json.id(), "json");
    }

    /// The forward and reverse directions agree.
    ///
    /// `from_extension` searches `extensions()`, so this cannot fail by
    /// construction today. It is written down anyway because the day someone
    /// reintroduces a hand-written match for speed, this is the test that says
    /// what the match now owes.
    #[test]
    fn every_listed_extension_resolves_to_the_language_that_lists_it() {
        for &language in Language::all() {
            for extension in language.extensions() {
                assert_eq!(
                    Language::from_extension(extension),
                    Some(language),
                    "{language:?} lists {extension:?}, which resolves elsewhere"
                );
            }
        }
    }

    #[test]
    fn no_extension_names_two_languages() {
        // This is what makes the scan order in `from_extension` irrelevant.
        // Compared exactly, not case-folded: `cpp` claims `"C"` and `c` claims
        // `"c"`, which are two extensions rather than one. `suffix::tests`
        // holds the separate guarantee that every case-folding clash is
        // resolved before the case-insensitive pass runs.
        let mut seen: Vec<(&str, Language)> = Vec::new();
        for &language in Language::all() {
            for extension in language.extensions() {
                if let Some((_, owner)) = seen.iter().find(|(name, _)| *name == extension) {
                    panic!("{extension:?} is claimed by both {owner:?} and {language:?}");
                }
                seen.push((extension, language));
            }
        }
    }

    #[test]
    fn every_extension_carries_no_dot() {
        // Callers pass what `Path::extension` returns, which never includes a
        // leading dot and never contains one. Case is *not* asserted: the
        // manifests carry `"C"`, `"H"` and `"MD"` deliberately, and
        // `from_extension` matches exactly before it folds case.
        for &language in Language::all() {
            assert!(
                language.extensions().next().is_some(),
                "{language:?} claims no extension, so no file can ever select it"
            );
            for extension in language.extensions() {
                assert!(
                    !extension.contains('.'),
                    "{language:?} lists {extension:?}, which is a file name rather \
                     than an extension"
                );
            }
        }
    }

    #[test]
    fn an_unknown_extension_is_none() {
        assert_eq!(Language::from_extension("cobol"), None);
        assert_eq!(Language::from_extension(""), None);
    }

    #[test]
    fn serialization_uses_the_lowercase_identifier() {
        // The wire form the web face and any serialized document share. It
        // must equal `id()`, or a document saved by one face names a language
        // another cannot read back.
        for &language in Language::all() {
            let json = serde_json::to_string(&language).expect("a language serializes");
            assert_eq!(json, format!("\"{}\"", language.id()), "{language:?}");
            let parsed: Language = serde_json::from_str(&json).expect("a language deserializes");
            assert_eq!(parsed, language);
        }
    }
}
